export const UI_STRUCTURE = {
  vaultSelection: {
    shell: 'vault-selection-shell',
    navigationRail: 'vault-selection-rail',
    mainPanel: 'vault-selection-main',
    actionGrid: 'vault-selection-actions',
    recentVaultModal: 'recent-vault-modal',
  },
  workspace: {
    shell: 'workspace-shell',
    navigationRail: 'workspace-rail',
    fileExplorer: 'notes-sidebar',
    fileExplorerHeader: 'vault-explorer-header',
    fileTree: 'vault-file-tree',
    contentPanel: 'workspace-content-panel',
    trashPage: 'trash-page',
    trashFiles: 'trash-files',
    tabBar: 'tab-strip',
    editor: 'editor-surface',
    noteHeader: 'editor-header',
    editorContent: 'editor-content',
  },
} as const

export const BUILDER_FRIENDLY_NAMES: Record<string, string> = {
  'vault-selection-shell': 'Tela de seleção de vault',
  'vault-selection-rail': 'Barra lateral da seleção',
  'vault-selection-actions': 'Ações de vault',
  'recent-vault-modal': 'Confirmação do último vault',
  'workspace-shell': 'Workspace de notas',
  'workspace-rail': 'Barra de ferramentas',
  'notes-sidebar': 'Explorador de arquivos',
  'vault-explorer-header': 'Cabeçalho do explorador do vault',
  'vault-file-tree': 'Árvore de arquivos do Vault',
  'trash-files': 'Arquivos da lixeira',
  'tab-strip': 'Barra de abas',
  'workspace-content-panel': 'Painel de conteúdo do workspace',
  'editor-header': 'Cabeçalho da nota',
  'editor-content': 'Editor da nota',
  'trash-page': 'Página da lixeira',
}
